version: 2

models:
  - name: customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
        meta:
          dimension:
            type: number
      - name: first_name
        description: Customer's first name
        meta:
          dimension:
            type: string
      - name: last_name
        description: Customer's last name
        meta:
          dimension:
            type: string
      - name: first_order_date
        description: Date of customer's first order. NULL when a customer has not yet placed an order.
        meta:
          dimension:
            type: date
      - name: most_recent_order_date
        description: Date of customer's most recent order
        meta:
          dimension:
            type: date
      - name: number_of_orders
        description: Total number of orders placed by the customer
        meta:
          dimension:
            type: number

  - name: stg_customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
        meta:
          dimension:
            type: number
      - name: first_name
        description: Customer's first name
        meta:
          dimension:
            type: string
      - name: last_name
        description: Customer's last name
        meta:
          dimension:
            type: string

  - name: stg_orders
    description: This model cleans up order data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
        meta:
          dimension:
            type: number
      - name: status
        description: Current status of the order
        tests:
          - accepted_values:
              values:
                - placed
                - shipped
                - completed
                - return_pending
                - returned
        meta:
          dimension:
            type: string
          metrics:
            total_order_count:
              type: count
      - name: customer_id
        description: Foreign key to stg_customers
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
        meta:
          dimension:
            type: number
      - name: order_date
        description: Date when the order was placed
        meta:
          dimension:
            type: date